const numberButton = document.querySelectorAll('[data-number')
const operationsButton = document.querySelectorAll('[data-operator')
const equalButton = document.querySelectorAll('[data-equal')
const clearButton = document.querySelectorAll('[data-clear')
const previousValueH2 = document.querySelectorAll('[data-previousvalue')
const displayValueH2 = document.querySelectorAll('[data-displayvalue')
